name: Docker image tests

on: push

jobs:
  docker-image-tests:
    name: Docker image tests
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build the image
        run: >
          docker build \
            -t pierky/arouteserver:latest \
            -f docker/Dockerfile \
            .

      - name: Run nosetests
        run: >
          docker run \
            -t \
            --rm \
            pierky/arouteserver:latest \
              nosetests -vsx tests/static

      - name: Run CLI tests
        run: >
          docker run \
            -t \
            --rm \
            pierky/arouteserver:latest \
              ./tests/cli

      - name: Prep environment for configuration building tests
        run: |
          mkdir ~/arouteserver_configs
          mkdir ~/arouteserver_html

      - name: Build configuration for BIRD 1.x
        run: >
          docker run \
            -t \
            --rm \
            -v $(pwd)/config.d/clients.yml:/root/clients.yml:ro \
            -v ~/arouteserver_configs:/root/arouteserver_configs \
            -e RS_ASN=65500 \
            -e ROUTER_ID=192.0.2.123 \
            -e LOCAL_PREFIXES=192.0.2.0/24,2001:db8::/32 \
            -e IP_VER=4 \
            -e DAEMON=bird \
            -e VERSION=1.6.8 \
            pierky/arouteserver:latest

      - name: Validate BIRD 1.x configuration
        run: >
          docker run \
            -t \
            --rm \
            -v ~/arouteserver_configs/bird4.cfg:/etc/bird/bird.cfg \
            pierky/bird:1.6.8 \
            bird \
              -c /etc/bird/bird.cfg \
              -d \
              -p

      - name: Build configuration for BIRD 2 (+ HTML representation)
        run: >
          docker run \
            -t \
            --rm \
            -v $(pwd)/config.d/clients.yml:/root/clients.yml:ro \
            -v ~/arouteserver_configs:/root/arouteserver_configs \
            -v ~/arouteserver_html:/root/arouteserver_html \
            -e RS_ASN=65500 \
            -e ROUTER_ID=192.0.2.123 \
            -e LOCAL_PREFIXES=192.0.2.0/24,2001:db8::/32 \
            -e DAEMON=bird \
            -e VERSION=2.0.7 \
            pierky/arouteserver:latest

      - name: Validate BIRD 2 configuration
        run: >
          docker run \
            -t \
            --rm \
            -v ~/arouteserver_configs/bird.cfg:/etc/bird/bird.cfg \
            pierky/bird:2.0.7 \
            bird \
              -c /etc/bird/bird.cfg \
              -d \
              -p

      - name: Validate HTML representation
        run: >
          grep \
            'Configuration of route server 192.0.2.123 at AS65500' \
            ~/arouteserver_html/bird.html &>/dev/null

      - name: Build configuration for OpenBGPD (+ HTML representation)
        run: >
          docker run \
            -t \
            --rm \
            -v $(pwd)/config.d/clients.yml:/root/clients.yml:ro \
            -v ~/arouteserver_configs:/root/arouteserver_configs \
            -v ~/arouteserver_html:/root/arouteserver_html \
            -e RS_ASN=65500 \
            -e ROUTER_ID=192.0.2.124 \
            -e LOCAL_PREFIXES=192.0.2.0/24,2001:db8::/32 \
            -e DAEMON=openbgpd \
            -e VERSION=6.7 \
            pierky/arouteserver:latest

      - name: Validate OpenBGPD configuration
        run: >
          docker run \
            -t \
            --rm \
            -v ~/arouteserver_configs/openbgpd.cfg:/etc/bgpd/bgpd.conf \
            pierky/openbgpd:6.7p0 \
            bgpd \
              -f /etc/bgpd/bgpd.conf \
              -d \
              -n

      - name: Validate HTML representation
        run: >
          grep \
            'Configuration of route server 192.0.2.124 at AS65500' \
            ~/arouteserver_html/openbgpd.html &>/dev/null

      - name: Build configuration using custom general.yml file
        run: >
          docker run \
            -t \
            --rm \
            -v $(pwd)/config.d/clients.yml:/root/clients.yml:ro \
            -v $(pwd)/examples/auto-config/bird-general.yml:/etc/arouteserver/general.yml:ro \
            -v ~/arouteserver_configs:/root/arouteserver_configs \
            -e IP_VER=4 \
            -e DAEMON=bird \
            -e VERSION=1.6.8 \
            pierky/arouteserver:latest

      - name: Validate configuration built using custom general.yml file
        run: >
          docker run \
            -t \
            --rm \
            -v ~/arouteserver_configs/bird4.cfg:/etc/bird/bird.cfg \
            pierky/bird:1.6.8 \
            bird \
              -c /etc/bird/bird.cfg \
              -d \
              -p

      - name: Build configuration using custom general.yml file with env vars and reject reasons communities
        run: >
          docker run \
            -t \
            --rm \
            -v $(pwd)/config.d/clients.yml:/root/clients.yml:ro \
            -v $(pwd)/tests/var/general-env-vars-and-reject-reasons.yml:/etc/arouteserver/general.yml:ro \
            -v ~/arouteserver_configs:/root/arouteserver_configs \
            -v ~/arouteserver_html:/root/arouteserver_html \
            -e IP_VER=4 \
            -e DAEMON=bird \
            -e VERSION=1.6.8 \
            -e RS_ASN=9999 \
            -e ROUTER_ID=192.0.2.200 \
            pierky/arouteserver:latest

      - name: Validate configuration built using custom general.yml file with env vars and reject reasons communities
        run: |
          docker run \
            -t \
            --rm \
            -v ~/arouteserver_configs/bird4.cfg:/etc/bird/bird.cfg \
            pierky/bird:1.6.8 \
            bird \
              -c /etc/bird/bird.cfg \
              -d \
              -p
          cat ~/arouteserver_configs/bird4.cfg | grep 'router id 192.0.2.200'

      - name: Validate HTML representation
        run: >
          grep \
            'Configuration of route server 192.0.2.200 at AS9999' \
            ~/arouteserver_html/bird.html &>/dev/null

      - name: Build configuration using local files
        run: >
          docker run \
            -t \
            --rm \
            -v $(pwd)/config.d/clients.yml:/root/clients.yml:ro \
            -v ~/arouteserver_configs:/root/arouteserver_configs \
            -e RS_ASN=65500 \
            -e ROUTER_ID=192.0.2.123 \
            -e LOCAL_PREFIXES=192.0.2.0/24,2001:db8::/32 \
            -e IP_VER=4 \
            -e DAEMON=bird \
            -e VERSION=1.6.8 \
            -e LOCAL_FILES="header footer" \
            -e LOCAL_FILES_DIR=/var/pierky/test \
            pierky/arouteserver:latest

      - name: Verify that include statements are there
        run: |
          cat ~/arouteserver_configs/bird4.cfg | \
            grep include | \
            grep /var/pierky/test | \
            egrep 'header.local|footer.local' | \
            wc -l | \
            grep 2
